spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${USERNAME}
    password: ${PASSWORD}
    url: jdbc:postgresql://localhost:5432/postgres
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: elinext
  main:
    allow-circular-references: true
logging:
  file:
    name: './logs/application-debug.log'
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    com:
      example:
        finalproject: INFO
    org.springframework.web: INFO
    org.hibernate: ERROR
server:
  servlet:
    context-path: /my-application
  port: ${PORT:8080}